### ISSUE TITLE
Getting error on startup

### ISSUE THREAD

**Issue by sidchh** [jimeh/.emacs.d#15]
Error (use-package): lsp-mode/:catch: Wrong type argument: listp
I get this when I startup after all the installation of all the packages/modules.
I am a noob to emacs. Any help would be appreciated 
Thanks

**Comment by sidchh** [comment]
28.2

**Comment by aneeshd9** [comment]
Hey, I was looking into this config for inspiration and I think I have narrowed this down to line 53 in .emacs.d/modules/lsp/siren-lsp.el, which is as follows:

(read-process-output-max (* 1024 1024))

Removing this line fixes the error for me.

I do not understand the reason for this yet tho.

P.S. I can open a PR for this if needed. It would be my first contribution to any other repo. :sweat_smile: Cheers.

**Comment by aneeshd9** [comment]
On looking further, I think I know the issue. The line should be in `:custom` section but it is under `:custom-face` section, which is causing the issue. Adding `:custom` block before `(read-process-output-max (* 1024 1024))` also fixes the issue.

**Comment by jimeh** [comment]
@aneeshd9 You're right 🤦‍♂️. Apologies for the hassle. This is now fixed in 7021114d558669d485d582ee16cada45ec35aeb7.

I've locally had a bunch of uncommitted and semi-finished tweaks to various things for an embarrassingly long time, and turns out one of those changes fixed this issue. I've had a look through and, and there shouldn't be anything else essential, hopefully 😅
